### ISSUE TITLE
Backwards compatibility with v1.5

### ISSUE THREAD

**Issue by robbens** [dw-interactive/mynewsdesk-wp-plugin#1]
How do we manage backwards compatibility with the current shortcodes, settings and front-end styles?

* Move settings upon update to new structure and names.
* Have the old shortcode `[mynewsdesk]` to display media in a similar way.
* Set same key names on query string for single media. _?media_type&view_id_

**Comment by j-falk** [comment]
Not applicable any more since we are creating this as a new plugin instead of build on top of the existing plugin.
