### ISSUE TITLE
Implement page selection to enable hooks and template routing for single media.

### ISSUE THREAD

**Issue by robbens** [dw-interactive/mynewsdesk-wp-plugin#2]
# The problem
When relying on shortcode to render the single media, we can't hook into `the_title()` and `the_post_thumbnail()`.

# Suggested approach
Set a page from the plugin settings to view the listing of media **and** use to view single  @media.

_Any feedback, inspiration or suggestions is greatly appreciated._

**Comment by j-falk** [comment]
Not applicable any more since we are going for a cpt approach
