### ISSUE TITLE
Use custom pretty permalinks for single media

### ISSUE THREAD

**Issue by robbens** [dw-interactive/mynewsdesk-wp-plugin#3]
The single media page is currently displayed using a query string, looking something like this: `/mynewsdesk/?type_of_media=news&id=12345`.

This isn't very SEO friendly or pretty at all. I'd like to use a slug;
`/mynewsdesk/news/this-is-an-awesome-article`.

How can this be achieved, the WordPress way, since we are fetching media from an external API?

**Comment by j-falk** [comment]
We could probably create a rewrite endpoint to achieve this? https://codex.wordpress.org/Rewrite_API/add_rewrite_endpoint

**Comment by robbens** [comment]
Just got to think of a bigger issue.
I can't fetch a single media based on a slug.

The only way to fetch it is by ID and type_of_media.
https://www.mynewsdesk.com/docs/webservice_pressroom#services_view

One way would be to use `/mynewsdesk/news/this-is-an-awesome-article?id=12345`.

**Comment by j-falk** [comment]
Not applicable any more since we are going for a cpt approach
